image: ruby:2.5

before_script:
  - apt-get update && apt-get install -y locales postgresql postgresql-client libpq-dev
  - echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
  - locale-gen
  - export LC_ALL=en_US.UTF-8

cibuild:
  script:
    - bin/cibuild

services:
  - postgres:latest

variables:
  DATABASE_URL: postgres://runner:password@postgres/proof
  POSTGRES_DB: proof
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: password
