image: ruby:2.6

before_script:
  - curl -sL https://deb.nodesource.com/setup_10.x | bash -
  - apt-get update && apt-get install -y locales postgresql postgresql-client libpq-dev nodejs unzip
  - echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
  - locale-gen
  - export LC_ALL=en_US.UTF-8
  - wget -q -O - https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
  - echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
  - apt-get update -yq
  - apt-get install -y yarn
  - ./bin/setup_chrome

cibuild:
  script:
    - bin/cibuild

services:
  - postgres:latest

variables:
  DATABASE_URL: postgres://runner:password@postgres/proof
  POSTGRES_DB: proof
  POSTGRES_USER: runner
  POSTGRES_PASSWORD: password
