# For a list of available cops see:
# https://github.com/bbatsov/rubocop/blob/master/config/default.yml
AllCops:
  TargetRubyVersion:
    2.5
  Exclude:
    - 'bin/**/*'
    - 'config/initializers/*.rb'
    - 'config/routes.rb'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'node_modules/**/*'
    - 'pkg/**/*'
    - 'spec/**/*'
    - 'test/**/*'
    - 'tmp/**/*'
    - 'vendor/**/*'

Metrics/AbcSize:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/RaiseArgs:
  EnforcedStyle: compact

Style/StringLiterals:
  Enabled: false

Style/SymbolArray:
  Enabled: false

Style/TrailingCommaInArrayLiteral:
  Enabled: false

Style/TrailingCommaInHashLiteral:
  Enabled: false

Style/TrailingCommaInArguments:
  Enabled: false
