sudo: false
language: ruby
addons:
  chrome: stable
rvm:
  - 2.5.3
before_script:
  - psql -c 'create database proof;' -U postgres
  - ln -s /usr/lib/chromium-browser/chromedriver ~/bin/chromedriver
env:
  - DATABASE_URL=postgres://postgres@localhost/proof
script:
  - bin/cibuild
services:
  - postgresql
