sudo: false
language: ruby
addons:
  chrome: stable
rvm:
  - 2.5.3
before_script:
  - psql -c 'create database proof;' -U postgres
env:
  - DATABASE_URL=postgres://postgres@localhsot/proof
script:
  - bin/cibuild
services:
  - postgresql
